baseURL = "/"
languageCode = "es-mx"
title = "rougon"

[outputs]
  page = ["json","players"]
  home = ["json", "redirect"]
  teams = ["json"]
  section = ["json"]
  taxonomy = ["json", "players"]

[outputFormats.players]
baseName = "players"
mediatype ="application/json"
[outputFormats.redirect]

baseName = "_redirects"
[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"
