baseURL = "/"
languageCode = "es-mx"
title = "rougon"

[outputs]
  page = ["json","players"]
  home = ["json", "redirect"]
  teams = ["json"]
  section = ["json"]
  taxonomy = ["json", "players"]

[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats.players]
baseName = "players"
mediatype ="application/json"
[outputFormats.redirect]
mediatype = "text/netlify"
baseName = "_redirects"
[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"
