baseURL = "/"
languageCode = "es-mx"
title = "aa"

[outputs]
  page = ["json","players","HTML"]
  home = ["json", "redirect"]
  teams = ["json"]
  section = ["json"]
  taxonomy = ["json", "players",HTML]

[outputFormats.players]
baseName = "players"
mediatype ="application/json"
[outputFormats.redirect]

baseName = "_redirects"
[taxonomies]
  sport = "sports"
  practice = "practices"

[permalinks]
  page = "/:section/:title/"
